language: ruby
cache: bundler
rvm:
- 2.3.2
deploy:
  skip_cleanup: true
  edge:
    source: criteo-forks/dpl
    branch: chef_ruby2
  provider: chef-supermarket
  user_id: criteo
  cookbook_category: Applications
  client_key: ".travis/client.pem"
  on:
    tags: true
env:
  global:
  - secure: h52Tqh2cu5RIwLTdhPglpJHLfE9jEYkp09mD4OOKHr6BHAmFmBE3VpCjXYgrSh6FnwhK+oOKyXrB3OQC3qAmPC9nE7lk0i4f8IxPotu8zoBa0hCc2YdepF9Rs3dduCJTxi2qGeFyComiOFHRL0LRzFSRA6I5RU8FJeSr6JmlLxMB7Rj0pJxbbUVhE/MIemawQe1hi3C+LRGkJeK8IFoqgDo3TaeN64xLRwOHcu4/7+4UZ091DT49U9un4j8MHzg10J7SLHd/OuKZ+/sk//gQz1hmAQzBc29WAORlcmMSkxUpFJiPrPUsXrNlbD54xvtcGb7m3s34JX0cTSOjPfApw7vWROI3I2XdI3hJZRwVX/qvUzjcmTNZrIT6eO4MjVCsPMTSVN1fjk2dvSLrq8c95Ii6VNd1RgVXZV7LaevLg9hf0Tcci37RyUjuq5nJQ8+xTDyL8H0Wj74q1kqvr+SkBsvG3ngJn9wJIWsBHtO2xQRo8lqebTmJ02mhqzbHaGeBidK8fxDvULwlkD3kGFxjhpxV8wlehyTIob4ztupQ9neWKf1lxA+6I25Wfg69sawWvuGId6NgKTBaQHzu6LSLNbJ7ZZI3fpkESoSBtmWQX/62ZH1h4VWsaIkOKTlnoT4v15TOZnf5SskwdbFW/ue2LRPlNLdp44tQNSXUzmer3oY=
  - secure: Hp/dnb7aMAeM3FrqHxtkS2h82biWfMY3cYXdVsksP6+nMMqDy8dqVeZboQivDtGVg89i1x52XgjpYb/eVprfQAvDMGVO95cvlJFBHikxEAUr0J2g/PAcVFI/5JgNAdp99zHnoXGU0MbqtLTkSpooDWT5lzqFn1fesWn7ZFsOm/9qVGZQI5HRzheEx66VsqbrufZCqddm4PVKzIY7hOLzH/wREUnpSoN7+e4eUvkRWT+1mDs2flbSCP6New9k37hqICN7gnMqx5B5p0NSYBxX7CfWSZtcZjRF8Rg3GCAXT1to1Vsyl9Pota5R7au1J/fDE/8jaYFfIOUwf2/8ANObZwkH9VZDeMRiIEbb0GR0krWa3mAgNHAs2eCSTldti69NXGV2K+/idPLN5pcwWMJ3ZaW1dlbCDF0yQ/L/AzP2DEj1BQ3aL5dgUWrddx075J5U6EiALN8GGNqvY6pUT0J19qNJRfkI800V7eI5xasrJPk1W6Ej6DqDFTIaOm9Fsazuy5VqB8w06xlbCHfqVnXWISzlRypfdQ7ZPki2IsVFKPcX1iF0AmlDw33s5JfasF8yUIIxupZube9j4odxkarNN5JJMz08VYS3oGdjRnDcvn2hzdCisEYOAfgOGtE5O3lcpW6zC20lUxcssn7WxvWi+GilUSkCqhgIC5MrUH9uwY4=
  - secure: 1XNO0hVpjZ1Q3kFQ13CqQr4iGF3gACWwGroAszyUXydOtOBb9p/NxpdYckd5USEBPGmB8qaXGQPs6NFia6nmo2s8m9xptyyPg9WTfx3GrzRCGNlx3k74OvbIs3oCHhZWMsvjIPXRNl4BkzZzE4YdW5MACD90y7Ny8vzEbJhu1ExrWWUHo/uJdv8BPopFQgcFKKAaM4qTGi7z6P/KPRlqQ8iIVDxjZwyeYexHd0s35DEteS9gRwVlwjvLRupM4EmOWn+TxishtgtkaeUP8WL+XK0qrlfg18GUfBm9PVuyQ+qPhg41oDqgGNWGmsK+d8DSHyliPJT6yzLxPKEIPv43hRCk2yGeayDJfEiEmkYha5vB5zQrm7v7LizwtVrGQvo3aNoCEEnQ6EueMTrvg5PSLeJbPNeeoeDiZwi/gTnCNDoFNDc4NhIA4W57cVxZKNDOSA7HzYSY9k7MElwmNCubxXJRhdLaECijmt9hx783I/aD9AH+Xy/8tP4RKG1P1cPSU5oLan2u+Na45XlnRUcxjL13TWng0lKG9SZMrAUcbvP6HnVuZnDkor+EZNl5lR3e7KXXV9yXQMBENgB/NpDzK6VO4sReaLe88nFsN4pO14HGNAWfX9vAMHIsNa2nXak0lQYclrbVWdxnFqaQIgV7cXxgKeO1l5vWwNGa22t6OuM=
  - secure: MMC2pn3fMpmATXoneLBPXvmyZV4osSZt+dPT19NSLD1CWkTjfL+VXCCCV/c4aWneIgxwuGQuw6dARD3R+FjYTfv73qQLNZOonN40QyVlRlcd0k6+6ChqWNcfILAqsS7YvDCpHiKyzDfwDMpn4Hv8qqxVVTbjFHAozusTmEzQ3/IhDznMi9LOezx7Yxt1N1IDMvOlzKy8SQplziBOnLVfVaMqdl0kdme12gex3OWuHGAnC7uUaXx34AIsRJopV/6T4/GuIehBJ+cBlzSSwj/XzfnRH1rTD/NKH7OaEqjtqT6OfFoTzvQCCkNbeoFpQQM/i2T8pIdfnJ39aESOC5Wc7T1IOBwRtz386XbkqXz5NqS6tyCSVPzIc+ZNeACVmEp4EoELNFdHK2+yUGbcrKHMSm4A7yRyh0htxhN06pFss2Ixs1vzGvVF/Okhni0xxxoMOSpuin4eqFzDVeCVw5NQ9K+zrWRRvmMGTM0yPh6mf9SU+qwMUjKxluE3DXr/SqcOah7oFlpSTKfTHORchzBqm0PjnEYJ9jwCnBlEYmsVajBWo1KSkNJwE3jQnwjopoygAb0RktOSnBwI31EYuSR7N8lmnj5Dliw9gtz/n4pBFYONVfvzIIUhZIMudDkaTjoQFi+C8x60+oad7xY+8fcL1d2AnTKXVHp66qKC5SQ30UI=
before_deploy:
- openssl aes-256-cbc -K $encrypted_eb3fc2d5c3da_key -iv $encrypted_eb3fc2d5c3da_iv
  -in .travis/client.pem.enc -out .travis/client.pem -d
before_install:
- openssl aes-256-cbc -K $encrypted_eb3fc2d5c3da_key -iv $encrypted_eb3fc2d5c3da_iv
  -in .travis/travis-ci.pem.enc -out .travis/travis-ci.pem.criteo -d
- cp -v .travis/travis-ci.pem.criteo ~/.ssh/id_rsa
